// <auto-generated />
namespace ReFreshAir1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removeconnstring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeconnstring));
        
        string IMigrationMetadata.Id
        {
            get { return "201812050005051_remove-connstring"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
